### ISSUE TITLE
stats initial value

### ISSUE THREAD

**Issue by brocolis** [LKedward/fhash#7]
Hi @LKedward. In the following code I'd expect the output _num_items : 0_

```fortran
program main
use fhash
implicit none

type(fhash_tbl_t) :: tbl
integer :: num_buckets, num_items, num_collisions, max_depth

call tbl%stats(num_buckets, num_items, num_collisions, max_depth)
print *, 'num_items:', num_items
  
end program main
```

The result is a big number:

![fhash](https://user-images.githubusercontent.com/5913872/107341640-fce1d380-6a9d-11eb-9b86-69e9e8a31581.png)

This happens on Windows 10.

**Comment by brocolis** [comment]
```fortran
num_items = 0
```
at line 7 solves the problem. 😇

**Comment by LKedward** [comment]
Hi @brocolis , thanks for reporting. This is a bug because you shouldn't need to initialise `num_items` before calling `tbl%stats`. I'll start on a fix.

**Comment by LKedward** [comment]
Thanks for finding this @brocolis, I've now fixed it in the latest version so you shouldn't need to add `num_items=0` anymore.

I think with *fpm* you can run `fpm update` to update your `fhash` dependency.
